version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: claims_qdrant
    ports:
      - "6333:6333" # Porta da API REST
      - "6334:6334" # Porta gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: always